services:
  redtable:
    build: .
    environment:
      PORT: 6380
      PROJECT: redtable-test-project
      INSTANCE: redtable-test-instance
      TABLE: redtable
    ports:
      - "6380:6380"
    volumes:
      - .:/src
    depends_on:
      redis:
        condition: service_started
      bigtable:
        condition: service_started
    healthcheck:
      test: ["CMD", "echo", "PING", "|", "nc", "localhost", "6380", "-q", "1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 2m
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  bigtable:
    image: "google/cloud-sdk"
    command: gcloud beta emulators bigtable start --host-port=0.0.0.0:8086
    ports:
      - "8086:8086"
  client:
    volumes:
      - .:/src
    build: 
      dockerfile: Dockerfile.client